#!/bin/bash


# NEW PATS 3: 1, 2, 4, 6, 12
# 2 PATS: 10, 14, 18
# SEED_LIST=(1 2 4 6 12)
#SEED_LIST=(1 2 4 6 12 20 21 22 23 24 25 26 27 28 29 30)
SEED_LIST=(1)
NUM_FEAT_PATTERNS_LIST=(3)
NUM_TRANSIENT_STEPS=100000
MAX_SIM_STEPS=$(($NUM_TRANSIENT_STEPS + 20000))
COMPUTE_INF_NORMALIZATION=True
NORMALIZE_WEIGHTS_STR_ATT="N**2*np.sqrt(M)"
NORMALIZE_WEIGHTS_STR_O="N"
CORRELATIONS_FROM_WEIGHTS=3
PE_MODE=0
NUM_SEGMENTS_CORRS=3
MIN_BETA=0
MAX_BETA=4
NUM_BETAS=1500
MIN_PE=0.02
MAX_PE=0.02
NUM_PES=1
PE_FROM_SIZE=True
TENTATIVE_SEMANTIC_EMBEDDING_SIZE=99
POSITIONAL_EMBEDDING_SIZE_LIST=(2)
SCALING_O=1
SCALING_ATT=10
INI_TOKEN_FROM_W=1

for SEED in "${SEED_LIST[@]}"; do
    for NUM_FEAT_PATTERNS in "${NUM_FEAT_PATTERNS_LIST[@]}"; do
        for POSITIONAL_EMBEDDING_SIZE in "${POSITIONAL_EMBEDDING_SIZE_LIST[@]}"; do
          echo $SEED $NUM_FEAT_PATTERNS $MAX_SIM_STEPS

          sbatch bifurcation_diagrams_inf.sh $SEED $NUM_FEAT_PATTERNS $NUM_TRANSIENT_STEPS $MAX_SIM_STEPS \
          $COMPUTE_INF_NORMALIZATION $NORMALIZE_WEIGHTS_STR_ATT $CORRELATIONS_FROM_WEIGHTS $PE_MODE $NUM_SEGMENTS_CORRS \
          $MIN_BETA $MAX_BETA $NUM_BETAS $MIN_PE $MAX_PE $NUM_PES $TENTATIVE_SEMANTIC_EMBEDDING_SIZE \
          $POSITIONAL_EMBEDDING_SIZE $PE_FROM_SIZE $NORMALIZE_WEIGHTS_STR_O $SCALING_O $SCALING_ATT \
          $INI_TOKEN_FROM_W
        done
    done
done
